'use strict';
const db=supabase.createClient('https://uftyyfrnqbeoyteafhxj.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdHl5ZnJucWJlb3l0ZWFmaHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExNTM5MDEsImV4cCI6MjA5NjcyOTkwMX0.y7WgJABO_QijcghWPKYPRiGlUZycXGuJMRQ5-XPv4d8');
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),clone=x=>JSON.parse(JSON.stringify(x));
const S={user:null,staff:false,board:null,edit:false,items:new Map(),pending:new Map(),seq:0,saving:false,timer:null,tool:'select',selected:null,gesture:null,view:{x:150,y:150,z:1},history:[],future:[],typing:null,publicToken:new URLSearchParams(location.hash.slice(1)).get('share'),generation:0,profiles:[],dirtyTitle:false};
const TEXT_TYPES=['note','card','text','shape'];
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').classList.remove('show'),4000)}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cleanHTML(html){const t=document.createElement('template');t.innerHTML=html||'';const allowed=new Set(['B','STRONG','I','EM','U','BR','DIV','P','SPAN','MARK','H2','UL','OL','LI']);function walk(root){for(const n of [...root.childNodes]){if(n.nodeType!==1)continue;if(!allowed.has(n.tagName)){n.replaceWith(document.createTextNode(n.textContent));continue}const bg=n.style.backgroundColor,weight=n.style.fontWeight;for(const a of [...n.attributes])n.removeAttribute(a.name);if(bg)n.style.backgroundColor=bg;if(weight==='bold'||Number(weight)>=600)n.style.fontWeight='bold';walk(n)}}walk(t.content);return t.innerHTML}
function safeURL(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function validItem(p){return p&&['note','card','text','shape','image','embed','edge'].includes(p.type)&& (p.type==='edge'?typeof p.from==='string'&&typeof p.to==='string'&&(!p.fromSide||['top','right','bottom','left'].includes(p.fromSide))&&(!p.toSide||['top','right','bottom','left'].includes(p.toSide)):['x','y','w','h'].every(k=>Number.isFinite(p[k])))}
function state(msg,error=false){$('save-state').textContent=msg;$('save-state').classList.toggle('error',error)}
function draftKey(){return `sa-studio-draft:${S.user?.id}:${S.board?.id}`}
function persist(){if(!S.user||!S.board)return;try{if(S.pending.size||S.dirtyTitle)localStorage.setItem(draftKey(),JSON.stringify({ops:[...S.pending],title:S.dirtyTitle?S.board.title:null}));else localStorage.removeItem(draftKey())}catch{state('Local backup full · keep this tab open',true)}}
function enqueue(id,p,deleted=false){if(!S.edit)return;const payload=clone(p);S.items.set(id,{id,payload,deleted});S.pending.set(id,{id,board_id:S.board.id,payload,deleted,seq:++S.seq});persist();state('Saving…');clearTimeout(S.timer);S.timer=setTimeout(flush,650)}
async function flush(){if(S.saving||!S.board||!S.edit)return !S.pending.size;S.saving=true;const bid=S.board.id;try{
 if(S.dirtyTitle&&S.staff){const title=S.board.title;const {data,error}=await db.from('studio_boards').update({title,updated_at:new Date().toISOString()}).eq('id',bid).select('id');if(error||!data?.length)throw error||new Error('Title permission denied');if(S.board.title===title)S.dirtyTitle=false}
 if(S.pending.size){const batch=[...S.pending.values()];const {data,error}=await db.from('studio_board_items').upsert(batch.map(({seq,...r})=>({...r,updated_at:new Date().toISOString()})),{onConflict:'id'}).select('id');if(error||data?.length!==batch.length)throw error||new Error('Not all changes were saved');for(const op of batch)if(S.pending.get(op.id)?.seq===op.seq)S.pending.delete(op.id)}
 persist();state(S.pending.size||S.dirtyTitle?'Saving…':'✓ All changes saved');return !S.pending.size&&!S.dirtyTitle;
 }catch(e){state(navigator.onLine?'Save failed · retrying':'Offline · changes kept on this device',true);console.warn('Board save:',e.message);return false}finally{S.saving=false;if(S.pending.size||S.dirtyTitle){clearTimeout(S.timer);S.timer=setTimeout(flush,4000)}}}
async function settled(){await flush();if(S.saving)await new Promise(r=>setTimeout(r,200));return !S.pending.size&&!S.dirtyTitle&&!S.saving}
function record(changes){S.history.push(changes);if(S.history.length>60)S.history.shift();S.future=[];updateUndo()}
function mutate(id,next){const old=S.items.get(id);record([{id,before:old&&!old.deleted?clone(old.payload):null,after:next?clone(next):null}]);enqueue(id,next||old.payload,!next);render()}
function undo(redo=false){if(!S.edit)return;const stack=redo?S.future:S.history,entry=stack.pop();if(!entry)return;(redo?S.history:S.future).push(entry);for(const c of entry){const p=redo?c.after:c.before;enqueue(c.id,p||c.after||c.before,!p)}render();updateUndo()}
function updateUndo(){$('undo').disabled=!S.edit||!S.history.length;$('redo').disabled=!S.edit||!S.future.length}
function activeItems(){return [...S.items.values()].filter(i=>!i.deleted&&validItem(i.payload))}
function point(e){const r=$('canvas').getBoundingClientRect();return {x:(e.clientX-r.left-S.view.x)/S.view.z,y:(e.clientY-r.top-S.view.y)/S.view.z}}
function center(){const r=$('canvas').getBoundingClientRect();return {x:(r.width/2-S.view.x)/S.view.z,y:(r.height/2-S.view.y)/S.view.z}}
function applyView(){$('world').style.transform=`translate(${S.view.x}px,${S.view.y}px) scale(${S.view.z})`;$('canvas').style.backgroundSize=`${24*S.view.z}px ${24*S.view.z}px`;$('canvas').style.backgroundPosition=`${S.view.x}px ${S.view.y}px`;$('zoom-value').textContent=Math.round(S.view.z*100)+'%';if(S.board)try{localStorage.setItem('studio-view:'+S.board.id,JSON.stringify(S.view))}catch{}}
function zoom(factor,cx,cy){const r=$('canvas').getBoundingClientRect(),x=cx??r.width/2,y=cy??r.height/2,z=Math.max(.15,Math.min(2.5,S.view.z*factor));S.view.x=x-(x-S.view.x)*z/S.view.z;S.view.y=y-(y-S.view.y)*z/S.view.z;S.view.z=z;applyView()}
function fit(){const nodes=activeItems().filter(i=>i.payload.type!=='edge');if(!nodes.length){S.view={x:150,y:150,z:1};applyView();return}const minx=Math.min(...nodes.map(i=>i.payload.x)),miny=Math.min(...nodes.map(i=>i.payload.y)),maxx=Math.max(...nodes.map(i=>i.payload.x+i.payload.w)),maxy=Math.max(...nodes.map(i=>i.payload.y+i.payload.h)),r=$('canvas').getBoundingClientRect();const z=Math.max(.15,Math.min(1.1,(r.width-200)/(maxx-minx||1),(r.height-200)/(maxy-miny||1)));S.view={z,x:(r.width-(maxx-minx)*z)/2-minx*z+20,y:(r.height-(maxy-miny)*z)/2-miny*z+25};applyView()}
function select(id){S.selected=id;document.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected',n.dataset.id===id));$('format').hidden=!id||!S.edit;const p=S.items.get(id)?.payload;document.querySelectorAll('[data-format]').forEach(b=>b.hidden=!p||!TEXT_TYPES.includes(p.type));$('duplicate').hidden=p?.type==='edge';drawEdges()}
function tool(name){S.tool=name;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===name));$('canvas').classList.toggle('connecting',name==='connect');S.connectFrom=null}
function nodeHTML(p){if(TEXT_TYPES.includes(p.type))return cleanHTML(p.html||'');if(p.type==='image'){const src=p.src||'';return /^data:image\/(png|jpeg|webp);base64,/.test(src)?`<img alt="Board reference" src="${src}">`:'Image unavailable'}const url=safeURL(p.url);if(!url)return 'Invalid link';const u=new URL(url);let src='';if(['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname)){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed)\/([\w-]+)/)?.[1];if(id&&/^[\w-]{6,}$/.test(id))src='https://www.youtube.com/embed/'+id}else if(u.hostname==='drive.google.com'){const id=u.pathname.match(/\/d\/([\w-]+)/)?.[1]||u.searchParams.get('id');if(id&&/^[\w-]+$/.test(id))src='https://drive.google.com/file/d/'+id+'/preview'}return src?`<iframe title="Embedded reference" src="${src}" loading="lazy" allow="fullscreen" allowfullscreen></iframe>`:`<a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">↗ ${escapeHTML(u.hostname)}<br><small>${escapeHTML(url)}</small></a>`}
function render(){const visible=activeItems(),nodes=visible.filter(i=>i.payload.type!=='edge');$('empty-canvas').hidden=!!nodes.length;const existing=new Map([...$('nodes').children].map(n=>[n.dataset.id,n]));for(const {id,payload:p} of nodes){let el=existing.get(id);if(!el){el=document.createElement('article');el.dataset.id=id;el.className='node '+p.type;el.innerHTML=`<div class="node-handle"><span>${p.type==='note'?'Idea':p.type==='card'?'Script':p.type}</span><span>⠿</span></div><div class="node-content" data-placeholder="Double-click to write…"></div>${['top','right','bottom','left'].map(side=>`<button class="port" data-side="${side}" aria-label="Connect from ${side}"></button>`).join('')}<div class="resize" aria-label="Resize card"></div>`;$('nodes').append(el)}existing.delete(id);el.classList.toggle('selected',id===S.selected);el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.width=Math.max(120,p.w)+'px';el.style.height=Math.max(80,p.h)+'px';el.style.setProperty('--node-color',/^#[0-9a-f]{6}$/i.test(p.color||'')?p.color:'#fff');const body=el.querySelector('.node-content');if(document.activeElement!==body){const content=nodeHTML(p);if(body.dataset.rendered!==content){body.innerHTML=content;body.dataset.rendered=content}}body.contentEditable='false';if(S.typing===id&&S.edit)body.contentEditable='true'}for(const el of existing.values())el.remove();drawEdges();updateUndo()}
function anchor(p,side){return side==='top'?{x:p.x+p.w/2,y:p.y}:side==='bottom'?{x:p.x+p.w/2,y:p.y+p.h}:side==='left'?{x:p.x,y:p.y+p.h/2}:{x:p.x+p.w,y:p.y+p.h/2}}
function curve(a,b,sa='right',sb='left'){const d=Math.max(50,Math.hypot(b.x-a.x,b.y-a.y)*.4),v={left:[-d,0],right:[d,0],top:[0,-d],bottom:[0,d]};return `M${a.x},${a.y} C${a.x+v[sa][0]},${a.y+v[sa][1]} ${b.x+v[sb][0]},${b.y+v[sb][1]} ${b.x},${b.y}`}
function drawEdges(){const layer=$('edge-layer');layer.replaceChildren();for(const i of activeItems().filter(i=>i.payload.type==='edge')){const e=i.payload,a=S.items.get(e.from),b=S.items.get(e.to);if(!a||!b||a.deleted||b.deleted||a.payload.type==='edge'||b.payload.type==='edge')continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',curve(anchor(a.payload,e.fromSide||'right'),anchor(b.payload,e.toSide||'left'),e.fromSide||'right',e.toSide||'left'));p.setAttribute('class','edge'+(S.selected===i.id?' selected':''));p.setAttribute('marker-end','url(#arrow)');p.dataset.id=i.id;if(/^#[0-9a-f]{6}$/i.test(e.color||''))p.style.stroke=e.color;layer.append(p)}}
function createNode(type,extra={}){if(!S.edit)return;const c=center(),p={type,x:Math.round(c.x-130),y:Math.round(c.y-90),w:type==='embed'?380:260,h:type==='embed'?260:type==='text'?120:190,color:type==='note'?'#fff1a8':type==='shape'?'#e8ddff':'#ffffff',html:'',...extra};const id=uid();mutate(id,p);select(id);tool('select');return id}
function connect(a,b,sa='right',sb='left'){if(a===b||!S.edit)return;const id=uid();mutate(id,{type:'edge',from:a,to:b,fromSide:sa,toSide:sb,color:'#9690b7'});select(id)}
function removeSelected(){if(!S.edit||!S.selected)return;const ids=[S.selected,...activeItems().filter(i=>i.payload.type==='edge'&&(i.payload.from===S.selected||i.payload.to===S.selected)).map(i=>i.id)],changes=[];for(const id of [...new Set(ids)]){const i=S.items.get(id);if(i&&!i.deleted){changes.push({id,before:clone(i.payload),after:null});enqueue(id,i.payload,true)}}record(changes);select(null);render()}
function duplicate(){const p=S.items.get(S.selected)?.payload;if(!p||p.type==='edge'||!S.edit)return;const id=uid();mutate(id,{...clone(p),x:p.x+35,y:p.y+35});select(id)}
$('canvas').addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;const node=e.target.closest('.node'),port=e.target.closest('.port'),edge=e.target.closest('.edge'),id=node?.dataset.id;if(e.target.closest('iframe,a')||e.target.isContentEditable)return;if(port&&S.edit){e.preventDefault();S.gesture={type:'connect',id,side:port.dataset.side};return}if(S.tool==='connect'&&id&&S.edit){if(S.connectFrom){connect(S.connectFrom,id);S.connectFrom=null;tool('select')}else{S.connectFrom=id;select(id);notify('Now click the card to connect to.')}return}if(edge){select(edge.dataset.id);return}if(id&&S.tool!=='pan'&&e.button===0){select(id);if(!S.edit)return;const p=S.items.get(id).payload;S.gesture={type:e.target.closest('.resize')?'resize':'move',id,start:point(e),before:clone(p)};e.preventDefault()}else{select(null);S.gesture={type:'pan',sx:e.clientX,sy:e.clientY,x:S.view.x,y:S.view.y};$('canvas').classList.add('panning');e.preventDefault()}});
window.addEventListener('pointermove',e=>{const g=S.gesture;if(!g)return;if(g.type==='pan'){S.view.x=g.x+e.clientX-g.sx;S.view.y=g.y+e.clientY-g.sy;applyView();return}const pos=point(e);if(g.type==='connect'){const p=S.items.get(g.id)?.payload;if(p)$('draft-edge').setAttribute('d',curve(anchor(p,g.side),pos,g.side,'left'));return}const p=S.items.get(g.id).payload;if(g.type==='move'){p.x=Math.round(g.before.x+pos.x-g.start.x);p.y=Math.round(g.before.y+pos.y-g.start.y)}else{p.w=Math.max(140,Math.round(g.before.w+pos.x-g.start.x));p.h=Math.max(90,Math.round(g.before.h+pos.y-g.start.y))}const el=document.querySelector(`.node[data-id="${g.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.width=p.w+'px';el.style.height=p.h+'px';drawEdges()});
window.addEventListener('pointerup',e=>{const g=S.gesture;S.gesture=null;$('canvas').classList.remove('panning');$('draft-edge').removeAttribute('d');if(!g)return;if(g.type==='connect'){const target=document.elementFromPoint(e.clientX,e.clientY),node=target?.closest('.node');if(node)connect(g.id,node.dataset.id,g.side,target.closest('.port')?.dataset.side||'left')}else if(g.type==='move'||g.type==='resize'){const p=S.items.get(g.id).payload;if(JSON.stringify(p)!==JSON.stringify(g.before)){record([{id:g.id,before:g.before,after:clone(p)}]);enqueue(g.id,p)}}});
$('canvas').addEventListener('wheel',e=>{e.preventDefault();const r=$('canvas').getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});
$('nodes').addEventListener('dblclick',e=>{const n=e.target.closest('.node'),body=e.target.closest('.node-content');if(!n||!body||!S.edit||!TEXT_TYPES.includes(S.items.get(n.dataset.id).payload.type))return;S.typing=n.dataset.id;S.textBefore=clone(S.items.get(S.typing).payload);body.contentEditable='true';body.focus();e.stopPropagation()});
$('nodes').addEventListener('input',e=>{const n=e.target.closest('.node');if(!n||!S.edit)return;const p=clone(S.items.get(n.dataset.id).payload);p.html=cleanHTML(e.target.innerHTML);enqueue(n.dataset.id,p)});
$('nodes').addEventListener('focusout',e=>{if(!e.target.classList.contains('node-content'))return;const id=e.target.closest('.node').dataset.id,p=S.items.get(id)?.payload;if(S.textBefore&&p&&S.textBefore.html!==p.html)record([{id,before:S.textBefore,after:clone(p)}]);S.textBefore=null;S.typing=null;e.target.contentEditable='false'});
$('nodes').addEventListener('paste',e=>{if(!e.target.isContentEditable)return;e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'))});
$('format').addEventListener('pointerdown',e=>{if(e.target.closest('[data-format]'))e.preventDefault()});
$('format').addEventListener('click',e=>{const fmt=e.target.closest('[data-format]'),col=e.target.closest('[data-color]');if(fmt&&S.typing){document.execCommand(fmt.dataset.format,false,fmt.dataset.format==='hiliteColor'?'#fff1a8':null);const body=document.querySelector(`.node[data-id="${S.typing}"] .node-content`);body.dispatchEvent(new Event('input',{bubbles:true}))}else if(fmt)notify('Double-click text, select words, then format.');if(col&&S.selected){const p=S.items.get(S.selected)?.payload;if(p)mutate(S.selected,{...p,color:col.dataset.color})}});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>createNode(b.dataset.add));$('first-note').onclick=()=>createNode('note');$('delete-item').onclick=removeSelected;$('duplicate').onclick=duplicate;$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);$('zoom-value').onclick=()=>zoom(1/S.view.z);
window.addEventListener('keydown',e=>{const editing=e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if(e.key==='Escape'){if(document.activeElement?.isContentEditable)document.activeElement.blur();tool('select');select(null);S.gesture=null;$('draft-edge').removeAttribute('d')}if($('studio').hidden||editing||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();flush()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected()}else if(e.key.toLowerCase()==='v')tool('select');else if(e.key.toLowerCase()==='h')tool('pan');else if(e.key.toLowerCase()==='l'&&S.edit)tool('connect');else if({n:'note',c:'card',t:'text'}[e.key.toLowerCase()])createNode({n:'note',c:'card',t:'text'}[e.key.toLowerCase()])});
$('add-embed').onclick=()=>$('embed-dialog').showModal();$('embed-form').onsubmit=e=>{e.preventDefault();const url=safeURL($('embed-url').value.trim());if(!url){notify('Enter an http or https link.');return}createNode('embed',{url});$('embed-dialog').close();$('embed-form').reset()};
$('add-image').onclick=()=>$('image-file').click();$('image-file').onchange=async()=>{const f=$('image-file').files[0],boardId=S.board?.id;if(!f)return;try{if(!f.type.startsWith('image/')||f.size>12*1024*1024)throw new Error('Choose an image under 12MB.');const bmp=await createImageBitmap(f),scale=Math.min(1,1400/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=bmp.width*scale;canvas.height=bmp.height*scale;canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);const src=canvas.toDataURL('image/webp',.85);bmp.close();if(src.length>2500000)throw new Error('Image is too large. Please use a smaller image.');if(S.board?.id!==boardId)return;createNode('image',{src,w:320,h:Math.max(150,Math.min(520,320*canvas.height/canvas.width+35))})}catch(e){notify(e.message)}finally{$('image-file').value=''}};
async function library(){if(S.board&&!await settled()){notify('Please wait until changes save before leaving this board.');return}S.generation++;S.board=null;S.items.clear();S.pending.clear();$('studio').hidden=true;$('library').hidden=false;$('status-screen').hidden=true;location.hash='';$('new-board').hidden=!S.staff;const {data,error}=await db.from('studio_boards').select('*').order('updated_at',{ascending:false});if(error){notify(error.message);return}S.boards=data||[];renderLibrary()}
function renderLibrary(){const query=$('search').value.toLowerCase(),boards=S.boards.filter(b=>b.title.toLowerCase().includes(query));$('board-count').textContent=S.boards.length;$('board-grid').innerHTML=(S.staff?'<button class="new-tile" id="new-tile"><b>＋</b>Create a new project<small>A blank canvas. Endless possibilities.</small></button>':'')+boards.map((b,i)=>`<article class="project-tile"><button class="project-open" data-open="${b.id}"><div class="tile-cover" style="filter:hue-rotate(${i*35%120}deg)"><svg viewBox="0 0 100 50"><path d="M0 10 C65 0 35 50 100 40" fill="none" stroke="#9d90c0" stroke-width="2"/></svg><div class="mini-card"></div><div class="mini-card second"></div></div><div class="tile-meta"><h3>${escapeHTML(b.title)}</h3><p>${new Date(b.updated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · ${b.share_token?'Link sharing on':'Private workspace'}</p></div></button>${S.staff?`<button class="tile-menu" data-delete="${b.id}" title="Delete project">×</button>`:''}</article>`).join('')+(!boards.length&&!S.staff?'<p class="empty-list">No shared projects yet. Your owner or manager can give you access.</p>':'');$('new-tile')?.addEventListener('click',()=>newDialog());document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openBoard(b.dataset.open).catch(e=>notify(e.message)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteBoard(b.dataset.delete))}
function newDialog(){$('project-dialog').showModal();$('project-name').focus()}
$('new-board').onclick=newDialog;$('search').oninput=renderLibrary;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('project-form').onsubmit=async e=>{e.preventDefault();const title=$('project-name').value.trim();if(!title||!S.staff)return;const button=e.submitter;button.disabled=true;try{const {data,error}=await db.from('studio_boards').insert({title,created_by:S.user.id}).select().single();if(error)throw error;$('project-dialog').close();await openBoard(data.id);if($('use-template').checked){const defs=[{type:'text',x:40,y:0,w:850,h:100,html:'Your next great video starts with a good story.',color:'#ffffff'},{type:'note',x:40,y:180,w:240,h:210,html:'<b>01 · THE HOOK</b><br><br>What makes someone stop scrolling?',color:'#fff1a8'},{type:'card',x:390,y:180,w:280,h:240,html:'<b>02 · THE STORY</b><br><br>Set the scene.<br>Build the curiosity.<br>Deliver the surprise.',color:'#ffffff'},{type:'note',x:780,y:180,w:240,h:210,html:'<b>03 · THE PAYOFF</b><br><br>Leave the viewer with one unforgettable thing.',color:'#e8ddff'}],ids=defs.map(p=>{const id=uid();enqueue(id,p);return id});enqueue(uid(),{type:'edge',from:ids[1],to:ids[2],fromSide:'right',toSide:'left',color:'#9690b7'});enqueue(uid(),{type:'edge',from:ids[2],to:ids[3],fromSide:'right',toSide:'left',color:'#9690b7'});render();fit();await flush()}$('project-form').reset();$('use-template').checked=true}catch(err){notify(err.message)}finally{button.disabled=false}};
async function deleteBoard(id){const b=S.boards.find(x=>x.id===id);if(!confirm(`Delete “${b.title}” and all its contents? This cannot be undone.`))return;const {error}=await db.from('studio_boards').delete().eq('id',id);if(error)notify(error.message);else library()}
async function openBoard(id){if(S.board&&!await settled()){notify('Wait for saving to finish.');return}const gen=++S.generation;state('Loading…');let board,items,canEdit=false;if(S.publicToken){const {data,error}=await db.rpc('read_shared_studio_board',{token:S.publicToken});if(error||!data)throw new Error('This sharing link is unavailable or has been disabled.');board=data;items=data.items}else{const [b,r]=await Promise.all([db.from('studio_boards').select('*').eq('id',id).single(),db.from('studio_board_items').select('*').eq('board_id',id)]);if(b.error||r.error)throw b.error||r.error;board=b.data;items=r.data;canEdit=S.staff;if(!canEdit){const {data}=await db.from('studio_board_members').select('can_edit').eq('board_id',id).eq('user_id',S.user.id).maybeSingle();canEdit=!!data?.can_edit}}if(gen!==S.generation)return;S.board=board;S.edit=canEdit;S.items=new Map((items||[]).filter(i=>validItem(i.payload)).map(i=>[i.id,i]));S.pending.clear();S.history=[];S.future=[];S.selected=null;S.typing=null;S.dirtyTitle=false;S.view={x:150,y:150,z:1};try{const v=JSON.parse(localStorage.getItem('studio-view:'+board.id));if(v&&[v.x,v.y,v.z].every(Number.isFinite)&&v.z>=.15&&v.z<=2.5)S.view=v;const draft=canEdit?JSON.parse(localStorage.getItem(draftKey())):null;if(draft){for(const [id,op] of draft.ops||[])if(validItem(op.payload)){S.items.set(id,{id,payload:op.payload,deleted:op.deleted});S.pending.set(id,{...op,seq:++S.seq})}if(draft.title&&S.staff){S.board.title=draft.title;S.dirtyTitle=true}notify('Recovered unsaved changes from this device.')}}catch{}
$('status-screen').hidden=true;$('library').hidden=true;$('studio').hidden=false;$('board-title').value=board.title;$('board-title').readOnly=!S.staff||!!S.publicToken;$('share').hidden=!S.staff||!!S.publicToken;$('back').hidden=!!S.publicToken;$('access-label').textContent=S.publicToken?'View only':canEdit?'Can edit':'Can view';$('studio').classList.toggle('readonly',!canEdit);document.querySelectorAll('.edit-only').forEach(b=>b.hidden=!canEdit);$('nodes').replaceChildren();select(null);render();let hadView=false;try{hadView=!!localStorage.getItem('studio-view:'+board.id)}catch{}applyView();if(!hadView)fit();if(!S.publicToken)location.hash='board='+board.id;state(S.pending.size?'Saving recovered changes…':'✓ All changes saved');if(S.pending.size||S.dirtyTitle)flush();}
$('back').onclick=()=>library();$('board-title').oninput=()=>{if(!S.staff||!S.board)return;S.board.title=$('board-title').value.trim()||'Untitled board';S.dirtyTitle=true;persist();state('Saving…');clearTimeout(S.timer);S.timer=setTimeout(flush,650)};
async function poll(){if(document.hidden||!S.board||S.gesture||S.typing||S.saving||S.pending.size||S.dirtyTitle)return;const bid=S.board.id,gen=S.generation;let rows;if(S.publicToken){const {data,error}=await db.rpc('read_shared_studio_board',{token:S.publicToken});if(error)return;if(!data){$('studio').hidden=true;$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>This sharing link has been disabled.</h2>';S.board=null;return}rows=data.items;$('board-title').value=data.title}else{const {data,error}=await db.from('studio_board_items').select('*').eq('board_id',bid);if(error)return;rows=data}if(gen!==S.generation||S.pending.size||S.typing||S.gesture)return;S.items=new Map((rows||[]).filter(i=>validItem(i.payload)).map(i=>[i.id,i]));if(S.selected&&!S.items.has(S.selected))select(null);render()}
setInterval(poll,30000);window.addEventListener('online',()=>{flush();poll()});window.addEventListener('beforeunload',e=>{if(S.pending.size||S.dirtyTitle){persist();e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.hidden){persist();flush()}else poll()});
$('share').onclick=async()=>{if(!S.staff||!S.board)return;$('share-dialog').showModal();await loadSharing()};
async function loadSharing(){const [users,members]=await Promise.all([db.from('profiles').select('id,name,email,role').order('name'),db.from('studio_board_members').select('*').eq('board_id',S.board.id)]);if(users.error||members.error){notify('Could not load sharing settings');return}S.profiles=users.data||[];const list=members.data||[];$('members').innerHTML='<div><span>Owners & managers</span><strong>Can edit</strong></div>'+list.map(m=>{const u=S.profiles.find(p=>p.id===m.user_id);return `<div><span>${escapeHTML(u?.name||u?.email||'Team member')}</span><strong>${m.can_edit?'Can edit':'Can view'}</strong><button data-remove="${m.user_id}">Remove</button></div>`}).join('');$('member-user').innerHTML=S.profiles.filter(p=>!['owner','manager'].includes(p.role)).map(p=>`<option value="${p.id}">${escapeHTML(p.name||p.email)}</option>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const {error}=await db.from('studio_board_members').delete().eq('board_id',S.board.id).eq('user_id',b.dataset.remove);if(error)notify(error.message);else loadSharing()});updatePublicLink()}
$('member-form').onsubmit=async e=>{e.preventDefault();const user_id=$('member-user').value;if(!user_id)return;const {error}=await db.from('studio_board_members').upsert({board_id:S.board.id,user_id,can_edit:$('member-permission').value==='true'});if(error)notify(error.message);else{notify('Access updated');loadSharing()}};
function updatePublicLink(){const token=S.board.share_token;$('enable-link').hidden=!!token;$('public-link-row').hidden=!token;if(token){const url=new URL(location.href);url.hash='share='+token;url.search='';$('public-link').value=url.href}}
$('enable-link').onclick=async()=>{const token=uid();const {data,error}=await db.from('studio_boards').update({share_token:token}).eq('id',S.board.id).select('id');if(error||!data?.length){notify('Could not enable sharing');return}S.board.share_token=token;updatePublicLink()};$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('public-link').value);notify('View-only link copied')}catch{$('public-link').select();notify('Select and copy the link above.')}};$('revoke-link').onclick=async()=>{const {data,error}=await db.from('studio_boards').update({share_token:null}).eq('id',S.board.id).select('id');if(error||!data?.length){notify('Could not disable link');return}S.board.share_token=null;updatePublicLink();notify('Public link disabled')};
async function init(){try{if(S.publicToken){await openBoard(null);return}const {data:{session},error}=await db.auth.getSession();if(error||!session){$('status-screen').innerHTML='<h2>Sign in to your workspace first.</h2><p><a href="index.html" target="_top">Open SA Media Empire</a></p>';return}S.user=session.user;const {data:profile,error:pe}=await db.from('profiles').select('name,role').eq('id',S.user.id).single();if(pe)throw pe;S.staff=['owner','manager'].includes(profile.role);$('identity').textContent=profile.name||session.user.email;const id=new URLSearchParams(location.hash.slice(1)).get('board');if(id)await openBoard(id);else await library()}catch(e){$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>Could not open this board.</h2><p>'+escapeHTML(e.message)+'</p><p><a href="board.html">Back to projects</a></p>'}}
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&!S.publicToken){persist();S.edit=false;$('studio').hidden=true;$('library').hidden=true;$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>You have signed out.</h2><p>Sign in again to open your boards.</p>'}});
init();
