'use strict';
const db=supabase.createClient('https://uftyyfrnqbeoyteafhxj.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdHl5ZnJucWJlb3l0ZWFmaHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExNTM5MDEsImV4cCI6MjA5NjcyOTkwMX0.y7WgJABO_QijcghWPKYPRiGlUZycXGuJMRQ5-XPv4d8');
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),clone=x=>JSON.parse(JSON.stringify(x));
const S={user:null,staff:false,board:null,edit:false,items:new Map(),pending:new Map(),seq:0,saving:false,timer:null,tool:'select',selected:null,gesture:null,view:{x:150,y:150,z:1},history:[],future:[],typing:null,publicToken:new URLSearchParams(location.hash.slice(1)).get('share'),generation:0,profiles:[],dirtyTitle:false};
const TEXT_TYPES=['note','card','text','shape'];
function notify(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').classList.remove('show'),4000)}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cleanHTML(html){
 const t=document.createElement('template');t.innerHTML=html||'';
 const allowed=new Set(['B','STRONG','I','EM','U','S','STRIKE','SUB','SUP','BR','DIV','P','SPAN','MARK','H1','H2','H3','UL','OL','LI','BLOCKQUOTE','A']);
 function walk(root){for(let n of [...root.childNodes]){if(n.nodeType!==1)continue;
 if(n.tagName==='FONT'){const span=document.createElement('span');span.innerHTML=n.innerHTML;span.style.color=n.getAttribute('color')||'';span.style.fontFamily=n.getAttribute('face')||'';const sizes=[0,10,13,16,18,24,32,48];if(n.getAttribute('size'))span.style.fontSize=(sizes[Number(n.getAttribute('size'))]||16)+'px';n.replaceWith(span);n=span}
 if(!allowed.has(n.tagName)){n.replaceWith(document.createTextNode(n.textContent));continue}
 const href=n.tagName==='A'?safeURL(n.getAttribute('href')):null;const st=n.style,keep={};for(const prop of ['color','backgroundColor','fontWeight','fontStyle','textDecoration','textAlign','fontSize','fontFamily','lineHeight','marginLeft']){const v=st[prop];if(v&&!/url|expression|var\(/i.test(v))keep[prop]=v}
 for(const a of [...n.attributes])n.removeAttribute(a.name);Object.assign(n.style,keep);if(href){n.href=href;n.target='_blank';n.rel='noopener noreferrer'}walk(n)}}walk(t.content);return t.innerHTML;
}
function safeURL(s){try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}}
function validItem(p){return p&&['note','card','text','shape','image','embed','edge'].includes(p.type)&& (p.type==='edge'?typeof p.from==='string'&&typeof p.to==='string'&&(!p.fromSide||['top','right','bottom','left'].includes(p.fromSide))&&(!p.toSide||['top','right','bottom','left'].includes(p.toSide)):['x','y','w','h'].every(k=>Number.isFinite(p[k])))}
function state(msg,error=false){$('save-state').textContent=msg;$('save-state').classList.toggle('error',error)}
function draftKey(){return `sa-studio-draft:${S.user?.id}:${S.board?.id}`}
function persist(){if(!S.user||!S.board)return;try{if(S.pending.size||S.dirtyTitle)localStorage.setItem(draftKey(),JSON.stringify({ops:[...S.pending],title:S.dirtyTitle?S.board.title:null}));else localStorage.removeItem(draftKey())}catch{state('Local backup full · keep this tab open',true)}}
function enqueue(id,p,deleted=false){if(!S.edit)return;const payload=clone(p);S.items.set(id,{id,payload,deleted});S.pending.set(id,{id,board_id:S.board.id,payload,deleted,seq:++S.seq});persist();state('Saving…');clearTimeout(S.timer);S.timer=setTimeout(flush,650)}
async function flush(){if(S.saving||!S.board||!S.edit)return !S.pending.size;S.saving=true;const bid=S.board.id;try{
 if(S.dirtyTitle&&S.staff){const title=S.board.title;const {data,error}=await db.from('studio_boards').update({title,updated_at:new Date().toISOString()}).eq('id',bid).select('id');if(error||!data?.length)throw error||new Error('Title permission denied');if(S.board.title===title)S.dirtyTitle=false}
 if(S.pending.size){const batch=[...S.pending.values()];const {data,error}=await db.from('studio_board_items').upsert(batch.map(({seq,...r})=>({...r,updated_at:new Date().toISOString()})),{onConflict:'id'}).select('id');if(error||data?.length!==batch.length)throw error||new Error('Not all changes were saved');for(const op of batch)if(S.pending.get(op.id)?.seq===op.seq)S.pending.delete(op.id)}
 persist();state(S.pending.size||S.dirtyTitle?'Saving…':'✓ All changes saved');return !S.pending.size&&!S.dirtyTitle;
 }catch(e){state(navigator.onLine?'Save failed · retrying':'Offline · changes kept on this device',true);console.warn('Board save:',e.message);return false}finally{S.saving=false;if(S.pending.size||S.dirtyTitle){clearTimeout(S.timer);S.timer=setTimeout(flush,4000)}}}
async function settled(){if(S.uploading)return false;await flush();if(S.saving)await new Promise(r=>setTimeout(r,200));return !S.pending.size&&!S.dirtyTitle&&!S.saving}
function record(changes){S.history.push(changes);if(S.history.length>60)S.history.shift();S.future=[];updateUndo()}
function mutate(id,next){const old=S.items.get(id);record([{id,before:old&&!old.deleted?clone(old.payload):null,after:next?clone(next):null}]);enqueue(id,next||old.payload,!next);render()}
function undo(redo=false){if(!S.edit)return;const stack=redo?S.future:S.history,entry=stack.pop();if(!entry)return;(redo?S.history:S.future).push(entry);for(const c of entry){const p=redo?c.after:c.before;enqueue(c.id,p||c.after||c.before,!p)}render();updateUndo()}
function updateUndo(){$('undo').disabled=!S.edit||!S.history.length;$('redo').disabled=!S.edit||!S.future.length}
function activeItems(){return [...S.items.values()].filter(i=>!i.deleted&&validItem(i.payload))}
function point(e){const r=$('canvas').getBoundingClientRect();return {x:(e.clientX-r.left-S.view.x)/S.view.z,y:(e.clientY-r.top-S.view.y)/S.view.z}}
function center(){const r=$('canvas').getBoundingClientRect();return {x:(r.width/2-S.view.x)/S.view.z,y:(r.height/2-S.view.y)/S.view.z}}
function applyView(){$('world').style.transform=`translate(${S.view.x}px,${S.view.y}px) scale(${S.view.z})`;$('canvas').style.backgroundSize=`${24*S.view.z}px ${24*S.view.z}px`;$('canvas').style.backgroundPosition=`${S.view.x}px ${S.view.y}px`;$('zoom-value').textContent=Math.round(S.view.z*100)+'%';if(S.board)try{localStorage.setItem('studio-view:'+S.board.id,JSON.stringify(S.view))}catch{}}
function zoom(factor,cx,cy){const r=$('canvas').getBoundingClientRect(),x=cx??r.width/2,y=cy??r.height/2,z=Math.max(.15,Math.min(2.5,S.view.z*factor));S.view.x=x-(x-S.view.x)*z/S.view.z;S.view.y=y-(y-S.view.y)*z/S.view.z;S.view.z=z;applyView();drawEdges()}
function fit(){const nodes=activeItems().filter(i=>i.payload.type!=='edge');if(!nodes.length){S.view={x:150,y:150,z:1};applyView();return}const minx=Math.min(...nodes.map(i=>i.payload.x)),miny=Math.min(...nodes.map(i=>i.payload.y)),maxx=Math.max(...nodes.map(i=>i.payload.x+i.payload.w)),maxy=Math.max(...nodes.map(i=>i.payload.y+i.payload.h)),r=$('canvas').getBoundingClientRect();const z=Math.max(.15,Math.min(1.1,(r.width-200)/(maxx-minx||1),(r.height-200)/(maxy-miny||1)));S.view={z,x:(r.width-(maxx-minx)*z)/2-minx*z+20,y:(r.height-(maxy-miny)*z)/2-miny*z+25};applyView()}
function select(id){S.selected=id;document.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected',n.dataset.id===id));$('format').hidden=!id||!S.edit;const p=S.items.get(id)?.payload;syncFormat(p);$('duplicate').hidden=p?.type==='edge';drawEdges()}
function tool(name){S.tool=name;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===name));$('canvas').classList.toggle('connecting',name==='connect');S.connectFrom=null}

function linkedHTML(html){const t=document.createElement('template');t.innerHTML=cleanHTML(html);const walk=document.createTreeWalker(t.content,NodeFilter.SHOW_TEXT),nodes=[];while(walk.nextNode())if(!walk.currentNode.parentElement?.closest('a'))nodes.push(walk.currentNode);for(const n of nodes){const text=n.textContent,re=/https?:\/\/[^\s<>]+|www\.[^\s<>]+/gi;let m,last=0,frag=document.createDocumentFragment(),found=false;while((m=re.exec(text))){const raw=m[0].replace(/[.,;!?)\]]+$/,'');const url=safeURL(raw.startsWith('www.')?'https://'+raw:raw);if(!url)continue;frag.append(text.slice(last,m.index));const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=raw;frag.append(a);last=m.index+raw.length;found=true}if(found){frag.append(text.slice(last));n.replaceWith(frag)}}return t.innerHTML}
function channelURL(value){try{const u=new URL(value);if(!['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))return null;const path=u.pathname.match(/^\/(?:@[\w.%-]+|channel\/[\w-]+|c\/[\w.%-]+|user\/[\w.%-]+)/)?.[0];return path?'https://www.youtube.com'+path:null}catch{return null}}
function channelCard(p){const url=channelURL(p.url);if(!url)return '';const name=p.channelName||new URL(url).pathname.split('/').pop(),logo=safeURL(p.channelLogo);return `<a class="channel-preview" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer"><span class="channel-kicker">YOUTUBE · CHANNEL</span><span class="channel-avatar">${logo?`<img alt="Channel logo" src="${escapeHTML(logo)}" referrerpolicy="no-referrer">`:'▶'}</span><strong>${escapeHTML(name)}</strong><span class="channel-description">${escapeHTML(p.channelDescription||'Competitor research · Channel reference')}</span><span class="channel-visit">Open channel ↗</span></a>`}

function nodeHTML(p){if(TEXT_TYPES.includes(p.type))return linkedHTML(p.html||'');if(p.type==='image'){const cached=imageURLs.get(p.storagePath),src=p.storagePath?cached?.url:(p.src||'');const safe=p.storagePath?!!cached?.url:/^data:image\/(png|jpeg|webp|gif|avif|bmp);base64,/.test(src||'');return `<div class="original-image">${safe?`<img alt="${escapeHTML(p.filename||'Board reference')}" src="${escapeHTML(src)}">`:'<span class="image-loading">Loading original image…</span>'}<button class="image-download" type="button" title="Download image at original quality">↓ Download${p.storagePath?' original':''}</button></div>`}if(channelURL(p.url))return channelCard(p);const url=safeURL(p.url);if(!url)return 'Invalid link';const u=new URL(url);let src='';if(['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname)){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed)\/([\w-]+)/)?.[1];if(id&&/^[\w-]{6,}$/.test(id))src='https://www.youtube.com/embed/'+id}else if(u.hostname==='drive.google.com'){const id=u.pathname.match(/\/d\/([\w-]+)/)?.[1]||u.searchParams.get('id');if(id&&/^[\w-]+$/.test(id))src='https://drive.google.com/file/d/'+id+'/preview'}return src?`<iframe title="Embedded reference" src="${src}" loading="lazy" allow="fullscreen" allowfullscreen></iframe>`:`<a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">↗ ${escapeHTML(u.hostname)}<br><small>${escapeHTML(url)}</small></a>`}
function render(){const visible=activeItems(),nodes=visible.filter(i=>i.payload.type!=='edge');$('empty-canvas').hidden=!!nodes.length;const existing=new Map([...$('nodes').children].map(n=>[n.dataset.id,n]));for(const {id,payload:p} of nodes){let el=existing.get(id);if(!el){el=document.createElement('article');el.dataset.id=id;el.className='node '+p.type;el.innerHTML=`<div class="node-handle"><span>${p.type==='note'?'Idea':p.type==='card'?'Script':p.type}</span><span>⠿</span></div><div class="node-content" data-placeholder="Double-click to write…"></div>${['top','right','bottom','left'].map(side=>`<button class="port" data-side="${side}" aria-label="Connect from ${side}"></button>`).join('')}<div class="resize" aria-label="Resize card"></div>`;$('nodes').append(el)}existing.delete(id);el.classList.toggle('selected',id===S.selected);el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.width=Math.max(120,p.w)+'px';el.style.height=Math.max(80,p.h)+'px';el.style.setProperty('--node-color',/^#[0-9a-f]{6}$/i.test(p.color||'')?p.color:'#fff');const body=el.querySelector('.node-content');if(document.activeElement!==body){const content=nodeHTML(p);if(body.dataset.rendered!==content){body.innerHTML=content;body.dataset.rendered=content}}el.style.zIndex=Number.isFinite(p.z)?p.z:0;if(p.type==='shape'){el.style.borderRadius=p.shape==='ellipse'?'50%':p.shape==='rectangle'?'3px':'35px';el.style.borderWidth=([0,1,2,4,6].includes(p.borderWidth)?p.borderWidth:2)+'px';el.style.borderStyle=['solid','dashed','dotted'].includes(p.borderStyle)?p.borderStyle:'solid';el.style.borderColor=/^#[0-9a-f]{6}$/i.test(p.borderColor||'')?p.borderColor:'#8b7eb7'}body.contentEditable='false';if(S.typing===id&&S.edit)body.contentEditable='true'}for(const el of existing.values())el.remove();drawEdges();updateUndo();hydrateImages()}
function anchor(p,side,at){if(at&&Number.isFinite(at.u)&&Number.isFinite(at.v))return {x:p.x+p.w*Math.max(0,Math.min(1,at.u)),y:p.y+p.h*Math.max(0,Math.min(1,at.v))};return side==='top'?{x:p.x+p.w/2,y:p.y}:side==='bottom'?{x:p.x+p.w/2,y:p.y+p.h}:side==='left'?{x:p.x,y:p.y+p.h/2}:{x:p.x+p.w,y:p.y+p.h/2}}
function curve(a,b,sa='right',sb='left'){const d=Math.max(50,Math.hypot(b.x-a.x,b.y-a.y)*.4),v={left:[-d,0],right:[d,0],top:[0,-d],bottom:[0,d]};return `M${a.x},${a.y} C${a.x+v[sa][0]},${a.y+v[sa][1]} ${b.x+v[sb][0]},${b.y+v[sb][1]} ${b.x},${b.y}`}
function drawEdges(){const layer=$('edge-layer');layer.replaceChildren();for(const i of activeItems().filter(i=>i.payload.type==='edge')){const e=i.payload,a=S.items.get(e.from),b=S.items.get(e.to);if(!a||!b||a.deleted||b.deleted||a.payload.type==='edge'||b.payload.type==='edge')continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',curve(anchor(a.payload,e.fromSide||'right',e.fromAnchor),anchor(b.payload,e.toSide||'left',e.toAnchor),e.fromSide||'right',e.toSide||'left'));p.setAttribute('class','edge'+(S.selected===i.id?' selected':''));p.setAttribute('marker-end','url(#arrow)');p.dataset.id=i.id;if(/^#[0-9a-f]{6}$/i.test(e.color||''))p.style.stroke=e.color;layer.append(p);if(S.edit&&S.selected===i.id){for(const end of ['from','to']){const pos=anchor(end==='from'?a.payload:b.payload,e[end+'Side']||(end==='from'?'right':'left'),e[end+'Anchor']);const handle=document.createElementNS('http://www.w3.org/2000/svg','circle');handle.setAttribute('cx',pos.x);handle.setAttribute('cy',pos.y);handle.setAttribute('r',7/S.view.z);handle.setAttribute('class','edge-endpoint');handle.dataset.id=i.id;handle.dataset.end=end;layer.append(handle)}}}}
function createNode(type,extra={}){if(!S.edit)return;const c=center(),p={type,x:Math.round(c.x-130),y:Math.round(c.y-90),w:type==='embed'?380:260,h:type==='embed'?260:type==='text'?120:190,color:type==='note'?'#fff1a8':type==='shape'?'#e8ddff':'#ffffff',html:'',...extra};const id=uid();mutate(id,p);select(id);tool('select');return id}
function connect(a,b,sa='right',sb='left',fromAnchor=null,toAnchor=null){if(a===b||!S.edit)return;const id=uid();mutate(id,{type:'edge',from:a,to:b,fromSide:sa,toSide:sb,fromAnchor,toAnchor,color:'#9690b7'});select(id)}
function removeSelected(){if(!S.edit||!S.selected)return;const ids=[S.selected,...activeItems().filter(i=>i.payload.type==='edge'&&(i.payload.from===S.selected||i.payload.to===S.selected)).map(i=>i.id)],changes=[];for(const id of [...new Set(ids)]){const i=S.items.get(id);if(i&&!i.deleted){changes.push({id,before:clone(i.payload),after:null});enqueue(id,i.payload,true)}}record(changes);select(null);render()}
function duplicate(){const p=S.items.get(S.selected)?.payload;if(!p||p.type==='edge'||!S.edit)return;const id=uid();mutate(id,{...clone(p),x:p.x+35,y:p.y+35});select(id)}
$('canvas').addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==1)return;const end=e.target.closest('.edge-endpoint');if(end&&S.edit){e.preventDefault();S.gesture={type:'endpoint',id:end.dataset.id,end:end.dataset.end,before:clone(S.items.get(end.dataset.id).payload)};return}const node=e.target.closest('.node'),port=e.target.closest('.port'),edge=e.target.closest('.edge'),id=node?.dataset.id;if(e.target.closest('.image-download'))return;if((e.target.closest('iframe,a')||e.target.isContentEditable)&&S.tool!=='connect')return;if(port&&S.edit){e.preventDefault();S.gesture={type:'connect',id,side:port.dataset.side,at:attachment(S.items.get(id).payload,point(e))};return}if(S.tool==='connect'&&id&&S.edit){if(S.connectFrom){const a=S.connectFrom,at=attachment(S.items.get(id).payload,point(e));connect(a.id,id,a.side,at.side,a.at,at);S.connectFrom=null;tool('select')}else{const at=attachment(S.items.get(id).payload,point(e));S.connectFrom={id,side:at.side,at};select(id);notify('Click anywhere on the destination card.')}return}if(edge){select(edge.dataset.id);return}if(id&&S.tool!=='pan'&&e.button===0){select(id);if(!S.edit)return;const p=S.items.get(id).payload;S.gesture={type:e.target.closest('.resize')?'resize':'move',id,start:point(e),before:clone(p)};e.preventDefault()}else{select(null);S.gesture={type:'pan',sx:e.clientX,sy:e.clientY,x:S.view.x,y:S.view.y};$('canvas').classList.add('panning');e.preventDefault()}});
window.addEventListener('pointermove',e=>{const g=S.gesture;if(!g)return;if(g.type==='pan'){S.view.x=g.x+e.clientX-g.sx;S.view.y=g.y+e.clientY-g.sy;applyView();return}const pos=point(e);if(g.type==='endpoint'){const old=g.before,other=g.end==='from'?'to':'from',node=S.items.get(old[other])?.payload;if(node){const fixed=anchor(node,old[other+'Side']||(other==='from'?'right':'left'),old[other+'Anchor']);$('draft-edge').setAttribute('d',g.end==='from'?curve(pos,fixed):curve(fixed,pos))}return}if(g.type==='connect'){const p=S.items.get(g.id)?.payload;if(p)$('draft-edge').setAttribute('d',curve(anchor(p,g.side,g.at),pos,g.side,'left'));return}const p=S.items.get(g.id).payload;if(g.type==='move'){p.x=Math.round(g.before.x+pos.x-g.start.x);p.y=Math.round(g.before.y+pos.y-g.start.y)}else{p.w=Math.max(140,Math.round(g.before.w+pos.x-g.start.x));p.h=Math.max(90,Math.round(g.before.h+pos.y-g.start.y))}const el=document.querySelector(`.node[data-id="${g.id}"]`);el.style.left=p.x+'px';el.style.top=p.y+'px';el.style.width=p.w+'px';el.style.height=p.h+'px';drawEdges()});
window.addEventListener('pointerup',e=>{const g=S.gesture;S.gesture=null;$('canvas').classList.remove('panning');$('draft-edge').removeAttribute('d');if(!g)return;if(g.type==='endpoint'){const target=nodeAt(e.clientX,e.clientY);if(target){const id=target.dataset.id,other=g.end==='from'?'to':'from';if(id!==g.before[other]){const at=attachment(S.items.get(id).payload,point(e));mutate(g.id,{...g.before,[g.end]:id,[g.end+'Anchor']:at,[g.end+'Side']:at.side})}}return}if(g.type==='connect'){const node=nodeAt(e.clientX,e.clientY);if(node){const at=attachment(S.items.get(node.dataset.id).payload,point(e));connect(g.id,node.dataset.id,g.side,at.side,g.at,at)}}else if(g.type==='move'||g.type==='resize'){const p=S.items.get(g.id).payload;if(JSON.stringify(p)!==JSON.stringify(g.before)){record([{id:g.id,before:g.before,after:clone(p)}]);enqueue(g.id,p)}}});
$('canvas').addEventListener('wheel',e=>{e.preventDefault();const r=$('canvas').getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});
$('nodes').addEventListener('dblclick',e=>{const n=e.target.closest('.node'),body=e.target.closest('.node-content');if(!n||!body||!S.edit||!TEXT_TYPES.includes(S.items.get(n.dataset.id).payload.type))return;S.typing=n.dataset.id;S.textBefore=clone(S.items.get(S.typing).payload);body.contentEditable='true';body.focus();e.stopPropagation()});
$('nodes').addEventListener('input',e=>{const n=e.target.closest('.node');if(!n||!S.edit)return;const p=clone(S.items.get(n.dataset.id).payload);p.html=cleanHTML(e.target.innerHTML);enqueue(n.dataset.id,p)});
$('nodes').addEventListener('focusout',e=>{if(!e.target.classList.contains('node-content'))return;const id=e.target.closest('.node').dataset.id,p=S.items.get(id)?.payload;if(S.textBefore&&p&&S.textBefore.html!==p.html)record([{id,before:S.textBefore,after:clone(p)}]);S.textBefore=null;S.typing=null;e.target.contentEditable='false';render()});
$('nodes').addEventListener('paste',e=>{if(!e.target.isContentEditable)return;e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'))});
/* Rich formatting and context menu are initialized below. */
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>createNode(b.dataset.add));$('first-note').onclick=()=>createNode('note');$('delete-item').onclick=removeSelected;$('duplicate').onclick=duplicate;$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);$('zoom-value').onclick=()=>zoom(1/S.view.z);
window.addEventListener('keydown',e=>{const editing=e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if(e.key==='Escape'){hideContext();if(document.activeElement?.isContentEditable)document.activeElement.blur();tool('select');select(null);S.gesture=null;$('draft-edge').removeAttribute('d')}if($('studio').hidden||editing||e.target.closest('#format')||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();flush()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected()}else if(e.key.toLowerCase()==='v')tool('select');else if(e.key.toLowerCase()==='h')tool('pan');else if(e.key.toLowerCase()==='l'&&S.edit)tool('connect');else if({n:'note',c:'card',t:'text'}[e.key.toLowerCase()])createNode({n:'note',c:'card',t:'text'}[e.key.toLowerCase()])});
$('add-embed').onclick=()=>{$('embed-form').reset();delete $('embed-form').dataset.editId;$('channel-fields').hidden=true;$('embed-status').textContent='';$('embed-dialog').showModal()};
$('embed-url').oninput=()=>{$('channel-fields').hidden=!channelURL($('embed-url').value.trim())};
$('embed-form').onsubmit=async e=>{e.preventDefault();const url=safeURL($('embed-url').value.trim());if(!url){notify('Enter an http or https link.');return}const channel=channelURL(url),bid=S.board?.id,editId=$('embed-form').dataset.editId,button=e.submitter||$('embed-form').querySelector('[type=submit]');button.disabled=true;let extra={url:channel||url};try{if(channel){extra={...extra,w:320,h:310,channelName:$('channel-name').value.trim(),channelLogo:safeURL($('channel-logo').value.trim())||''};$('embed-status').textContent='Loading channel preview…';try{const {data,error}=await db.functions.invoke('studio-channel-preview',{body:{url:channel,board_id:bid}});if(!error&&data?.name){extra.channelName=extra.channelName||data.name;extra.channelLogo=extra.channelLogo||data.logo;extra.channelDescription=data.description}else notify('Preview unavailable. You can set the channel name and logo using Edit link.')}catch{notify('Preview unavailable. You can set the channel name and logo using Edit link.')}}if(S.board?.id!==bid)return;if(editId&&S.items.has(editId)){const old=S.items.get(editId).payload;mutate(editId,{...old,...extra,w:old.w,h:old.h})}else createNode('embed',extra);$('embed-dialog').close();$('embed-form').reset()}finally{button.disabled=false;$('embed-status').textContent=''}};
$('nodes').addEventListener('dblclick',e=>{const node=e.target.closest('.node');if(!node||!S.edit||e.target.closest('a,iframe'))return;const p=S.items.get(node.dataset.id)?.payload;if(p?.type!=='embed')return;$('embed-form').dataset.editId=node.dataset.id;$('embed-url').value=p.url||'';$('channel-name').value=p.channelName||'';$('channel-logo').value=p.channelLogo||'';$('channel-fields').hidden=!channelURL(p.url);$('embed-dialog').showModal()});

$('add-image').onclick=()=>$('image-file').click();$('image-file').onchange=async()=>{
 const f=$('image-file').files[0],bid=S.board?.id;if(!f||!S.edit)return;
 S.uploading=true;$('add-image').disabled=true;try{
  const allowed=['image/png','image/jpeg','image/webp','image/gif','image/avif','image/bmp'];if(!allowed.includes(f.type))throw new Error('Choose a PNG, JPEG, WebP, GIF, AVIF or BMP image.');
  if(f.size>20*1024*1024)throw new Error('The original must be under 20 MB. It will not be compressed.');
  notify('Uploading original image…');const ext={"image/png":"png","image/jpeg":"jpg","image/webp":"webp","image/gif":"gif","image/avif":"avif","image/bmp":"bmp"}[f.type],path=bid+'/'+uid()+'.'+ext;
  const {error}=await db.storage.from('studio-originals').upload(path,f,{contentType:f.type,upsert:false,cacheControl:'3600'});if(error)throw error;
  if(S.board?.id!==bid)throw new Error('Board changed during upload. Add the image again in the intended board.');
  const preview=URL.createObjectURL(f);imageURLs.set(path,{url:preview,until:Date.now()+240000,local:true});
  let ratio=1;try{const bitmap=await createImageBitmap(f);ratio=bitmap.height/bitmap.width;bitmap.close()}catch{}
  createNode('image',{storagePath:path,filename:f.name,mime:f.type,bytes:f.size,w:360,h:Math.max(180,Math.min(560,360*ratio+70))});
  await flush();notify('Original image added · no compression');
 }catch(e){notify(e.message)}finally{S.uploading=false;$('add-image').disabled=false;$('image-file').value=''}
};

async function library(){if(S.board&&!await settled()){notify('Please wait until changes save before leaving this board.');return}S.generation++;S.board=null;S.items.clear();S.pending.clear();$('studio').hidden=true;$('library').hidden=false;$('status-screen').hidden=true;location.hash='';$('new-board').hidden=!S.staff;const {data,error}=await db.from('studio_boards').select('*').order('updated_at',{ascending:false});if(error){notify(error.message);return}S.boards=data||[];renderLibrary()}
function renderLibrary(){const query=$('search').value.toLowerCase(),boards=S.boards.filter(b=>b.title.toLowerCase().includes(query));$('board-count').textContent=S.boards.length;$('board-grid').innerHTML=(S.staff?'<button class="new-tile" id="new-tile"><b>＋</b>Create a new project<small>A blank canvas. Endless possibilities.</small></button>':'')+boards.map((b,i)=>`<article class="project-tile"><button class="project-open" data-open="${b.id}"><div class="tile-cover" style="filter:hue-rotate(${i*35%120}deg)"><svg viewBox="0 0 100 50"><path d="M0 10 C65 0 35 50 100 40" fill="none" stroke="#9d90c0" stroke-width="2"/></svg><div class="mini-card"></div><div class="mini-card second"></div></div><div class="tile-meta"><h3>${escapeHTML(b.title)}</h3><p>${new Date(b.updated_at).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · ${b.share_token?'Link sharing on':'Private workspace'}</p></div></button>${S.staff?`<button class="tile-menu" data-delete="${b.id}" title="Delete project">×</button>`:''}</article>`).join('')+(!boards.length&&!S.staff?'<p class="empty-list">No shared projects yet. Your owner or manager can give you access.</p>':'');$('new-tile')?.addEventListener('click',()=>newDialog());document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openBoard(b.dataset.open).catch(e=>notify(e.message)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteBoard(b.dataset.delete))}
function newDialog(){$('project-dialog').showModal();$('project-name').focus()}
$('new-board').onclick=newDialog;$('search').oninput=renderLibrary;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('project-form').onsubmit=async e=>{e.preventDefault();const title=$('project-name').value.trim();if(!title||!S.staff)return;const button=e.submitter;button.disabled=true;try{const {data,error}=await db.from('studio_boards').insert({title,created_by:S.user.id}).select().single();if(error)throw error;$('project-dialog').close();await openBoard(data.id);if($('use-template').checked){const defs=[{type:'text',x:40,y:0,w:850,h:100,html:'Your next great video starts with a good story.',color:'#ffffff'},{type:'note',x:40,y:180,w:240,h:210,html:'<b>01 · THE HOOK</b><br><br>What makes someone stop scrolling?',color:'#fff1a8'},{type:'card',x:390,y:180,w:280,h:240,html:'<b>02 · THE STORY</b><br><br>Set the scene.<br>Build the curiosity.<br>Deliver the surprise.',color:'#ffffff'},{type:'note',x:780,y:180,w:240,h:210,html:'<b>03 · THE PAYOFF</b><br><br>Leave the viewer with one unforgettable thing.',color:'#e8ddff'}],ids=defs.map(p=>{const id=uid();enqueue(id,p);return id});enqueue(uid(),{type:'edge',from:ids[1],to:ids[2],fromSide:'right',toSide:'left',color:'#9690b7'});enqueue(uid(),{type:'edge',from:ids[2],to:ids[3],fromSide:'right',toSide:'left',color:'#9690b7'});render();fit();await flush()}$('project-form').reset();$('use-template').checked=true}catch(err){notify(err.message)}finally{button.disabled=false}};
async function deleteBoard(id){const b=S.boards.find(x=>x.id===id);if(!confirm(`Delete “${b.title}” and all its contents? This cannot be undone.`))return;const {error}=await db.from('studio_boards').delete().eq('id',id);if(error)notify(error.message);else library()}
async function openBoard(id){if(S.board&&!await settled()){notify('Wait for saving to finish.');return}const gen=++S.generation;state('Loading…');let board,items,canEdit=false;if(S.publicToken){const {data,error}=await db.rpc('read_shared_studio_board',{token:S.publicToken});if(error||!data)throw new Error('This sharing link is unavailable or has been disabled.');board=data;items=data.items}else{const [b,r]=await Promise.all([db.from('studio_boards').select('*').eq('id',id).single(),db.from('studio_board_items').select('*').eq('board_id',id)]);if(b.error||r.error)throw b.error||r.error;board=b.data;items=r.data;canEdit=S.staff;if(!canEdit){const {data}=await db.from('studio_board_members').select('can_edit').eq('board_id',id).eq('user_id',S.user.id).maybeSingle();canEdit=!!data?.can_edit}}if(gen!==S.generation)return;S.board=board;S.edit=canEdit;S.items=new Map((items||[]).filter(i=>validItem(i.payload)).map(i=>[i.id,i]));S.pending.clear();S.history=[];S.future=[];S.selected=null;S.typing=null;S.dirtyTitle=false;S.view={x:150,y:150,z:1};try{const v=JSON.parse(localStorage.getItem('studio-view:'+board.id));if(v&&[v.x,v.y,v.z].every(Number.isFinite)&&v.z>=.15&&v.z<=2.5)S.view=v;const draft=canEdit?JSON.parse(localStorage.getItem(draftKey())):null;if(draft){for(const [id,op] of draft.ops||[])if(validItem(op.payload)){S.items.set(id,{id,payload:op.payload,deleted:op.deleted});S.pending.set(id,{...op,seq:++S.seq})}if(draft.title&&S.staff){S.board.title=draft.title;S.dirtyTitle=true}notify('Recovered unsaved changes from this device.')}}catch{}
$('status-screen').hidden=true;$('library').hidden=true;$('studio').hidden=false;$('board-title').value=board.title;$('board-title').readOnly=!S.staff||!!S.publicToken;$('share').hidden=!S.staff||!!S.publicToken;$('back').hidden=!!S.publicToken;$('access-label').textContent=S.publicToken?'View only':canEdit?'Can edit':'Can view';$('studio').classList.toggle('readonly',!canEdit);document.querySelectorAll('.edit-only').forEach(b=>b.hidden=!canEdit);$('nodes').replaceChildren();select(null);render();let hadView=false;try{hadView=!!localStorage.getItem('studio-view:'+board.id)}catch{}applyView();if(!hadView)fit();if(!S.publicToken)location.hash='board='+board.id;state(S.pending.size?'Saving recovered changes…':'✓ All changes saved');if(S.pending.size||S.dirtyTitle)flush();}
$('back').onclick=()=>library();$('board-title').oninput=()=>{if(!S.staff||!S.board)return;S.board.title=$('board-title').value.trim()||'Untitled board';S.dirtyTitle=true;persist();state('Saving…');clearTimeout(S.timer);S.timer=setTimeout(flush,650)};
async function poll(){if(document.hidden||!S.board||S.gesture||S.typing||S.saving||S.pending.size||S.dirtyTitle)return;const bid=S.board.id,gen=S.generation;let rows;if(S.publicToken){const {data,error}=await db.rpc('read_shared_studio_board',{token:S.publicToken});if(error)return;if(!data){$('studio').hidden=true;$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>This sharing link has been disabled.</h2>';S.board=null;return}rows=data.items;$('board-title').value=data.title}else{const [items,board]=await Promise.all([db.from('studio_board_items').select('*').eq('board_id',bid),db.from('studio_boards').select('title').eq('id',bid).maybeSingle()]);if(gen!==S.generation)return;if(items.error||board.error)return;if(!board.data){S.edit=false;S.items.clear();$('studio').hidden=true;$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>This board is no longer available to you.</h2><p><a href="board.html">Back to projects</a></p>';S.board=null;return}if(!S.staff){const {data:membership,error:memberError}=await db.from('studio_board_members').select('can_edit').eq('board_id',bid).eq('user_id',S.user.id).maybeSingle();if(memberError||gen!==S.generation)return;S.edit=!!membership?.can_edit;$('studio').classList.toggle('readonly',!S.edit);document.querySelectorAll('.edit-only').forEach(b=>b.hidden=!S.edit);$('access-label').textContent=S.edit?'Can edit':'Can view';if(!S.edit)select(null)}if(!S.dirtyTitle){S.board.title=board.data.title;$('board-title').value=board.data.title}rows=items.data}if(gen!==S.generation||S.pending.size||S.typing||S.gesture)return;S.items=new Map((rows||[]).filter(i=>validItem(i.payload)).map(i=>[i.id,i]));if(S.selected&&!S.items.has(S.selected))select(null);render()}
setInterval(poll,30000);window.addEventListener('online',()=>{flush();poll()});window.addEventListener('beforeunload',e=>{if(S.uploading||S.pending.size||S.dirtyTitle){persist();e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.hidden){persist();flush()}else poll()});
$('share').onclick=async()=>{if(!S.staff||!S.board)return;$('share-dialog').showModal();await loadSharing()};
async function loadSharing(){const [users,members]=await Promise.all([db.from('profiles').select('id,name,email,role').order('name'),db.from('studio_board_members').select('*').eq('board_id',S.board.id)]);if(users.error||members.error){notify('Could not load sharing settings');return}S.profiles=users.data||[];const list=members.data||[];$('members').innerHTML='<div><span>Owners & managers</span><strong>Can edit</strong></div>'+list.map(m=>{const u=S.profiles.find(p=>p.id===m.user_id);return `<div><span>${escapeHTML(u?.name||u?.email||'Team member')}</span><strong>${m.can_edit?'Can edit':'Can view'}</strong><button data-remove="${m.user_id}">Remove</button></div>`}).join('');$('member-user').innerHTML=S.profiles.filter(p=>!['owner','manager'].includes(p.role)).map(p=>`<option value="${p.id}">${escapeHTML(p.name||p.email)}</option>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const {error}=await db.from('studio_board_members').delete().eq('board_id',S.board.id).eq('user_id',b.dataset.remove);if(error)notify(error.message);else loadSharing()});updatePublicLink()}
$('member-form').onsubmit=async e=>{e.preventDefault();const user_id=$('member-user').value;if(!user_id)return;const {error}=await db.from('studio_board_members').upsert({board_id:S.board.id,user_id,can_edit:$('member-permission').value==='true'});if(error)notify(error.message);else{notify('Access updated');loadSharing()}};
function updatePublicLink(){const token=S.board.share_token;$('enable-link').hidden=!!token;$('public-link-row').hidden=!token;if(token){const url=new URL(location.href);url.hash='share='+token;url.search='';$('public-link').value=url.href}}
$('enable-link').onclick=async()=>{const token=uid();const {data,error}=await db.from('studio_boards').update({share_token:token}).eq('id',S.board.id).select('id');if(error||!data?.length){notify('Could not enable sharing');return}S.board.share_token=token;updatePublicLink()};$('copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('public-link').value);notify('View-only link copied')}catch{$('public-link').select();notify('Select and copy the link above.')}};$('revoke-link').onclick=async()=>{const {data,error}=await db.from('studio_boards').update({share_token:null}).eq('id',S.board.id).select('id');if(error||!data?.length){notify('Could not disable link');return}S.board.share_token=null;updatePublicLink();notify('Public link disabled')};
async function init(){try{if(S.publicToken){await openBoard(null);return}const {data:{session},error}=await db.auth.getSession();if(error||!session){$('status-screen').innerHTML='<h2>Sign in to your workspace first.</h2><p><a href="index.html" target="_top">Open SA Media Empire</a></p>';return}S.user=session.user;const {data:profile,error:pe}=await db.from('profiles').select('name,role').eq('id',S.user.id).single();if(pe)throw pe;S.staff=['owner','manager'].includes(profile.role);$('identity').textContent=profile.name||session.user.email;const id=new URLSearchParams(location.hash.slice(1)).get('board');if(id)await openBoard(id);else await library()}catch(e){$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>Could not open this board.</h2><p>'+escapeHTML(e.message)+'</p><p><a href="board.html">Back to projects</a></p>'}}
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&!S.publicToken){persist();S.edit=false;$('studio').hidden=true;$('library').hidden=true;$('status-screen').hidden=false;$('status-screen').innerHTML='<h2>You have signed out.</h2><p>Sign in again to open your boards.</p>'}});
function nodeAt(x,y){return (document.elementsFromPoint?document.elementsFromPoint(x,y):[document.elementFromPoint(x,y)]).map(el=>el?.closest('.node')).find(Boolean)}
function attachment(p,pos){const u=Math.max(0,Math.min(1,(pos.x-p.x)/p.w)),v=Math.max(0,Math.min(1,(pos.y-p.y)/p.h));const distances={left:u,right:1-u,top:v,bottom:1-v};return {u,v,side:Object.keys(distances).sort((a,b)=>distances[a]-distances[b])[0]}}
function syncFormat(p){document.querySelectorAll('.text-options').forEach(el=>el.hidden=!p||!TEXT_TYPES.includes(p.type));document.querySelector('.shape-options').hidden=p?.type!=='shape';document.querySelector('.edge-options').hidden=p?.type!=='edge';if(!p)return;$('fill-color').value=/^#[0-9a-f]{6}$/i.test(p.color||'')?p.color:'#ffffff';if(p.type==='shape'){$('shape-kind').value=p.shape||'rounded';$('border-color').value=p.borderColor||'#8b7eb7';$('border-width').value=p.borderWidth??2;$('border-style').value=p.borderStyle||'solid'}}
let savedTextRange=null,contextPoint=null,boardClipboard=null;
document.addEventListener('selectionchange',()=>{const sel=window.getSelection();if(!sel?.rangeCount)return;const range=sel.getRangeAt(0),el=range.commonAncestorContainer.nodeType===1?range.commonAncestorContainer:range.commonAncestorContainer.parentElement,body=el?.closest('.node-content');if(body)savedTextRange={id:body.closest('.node').dataset.id,range:range.cloneRange()}});
function rich(command,value=null){if(!S.edit||!S.selected)return;const id=S.selected,item=S.items.get(id);if(!item||!TEXT_TYPES.includes(item.payload.type))return;const body=document.querySelector(`.node[data-id="${id}"] .node-content`),before=clone(item.payload);if(S.typing===id&&S.textBefore&&S.textBefore.html!==before.html)record([{id,before:clone(S.textBefore),after:clone(before)}]);body.contentEditable='true';S.typing=id;S.textBefore=clone(before);body.focus();const sel=window.getSelection();sel.removeAllRanges();const saved=savedTextRange;if(saved?.id===id&&body.contains(saved.range.commonAncestorContainer)){sel.addRange(saved.range)}else{const range=document.createRange();range.selectNodeContents(body);sel.addRange(range)}
 // A toolbar action without a text selection formats the whole card.
 if(sel.isCollapsed&&body.textContent){const range=document.createRange();range.selectNodeContents(body);sel.removeAllRanges();sel.addRange(range)}
 document.execCommand('styleWithCSS',false,true);
 if(command==='size'){document.execCommand('styleWithCSS',false,false);document.execCommand('fontSize',false,'7');body.querySelectorAll('font[size="7"]').forEach(n=>{const span=document.createElement('span');span.style.fontSize=Number(value)+'px';while(n.firstChild)span.append(n.firstChild);n.replaceWith(span)})}
 else document.execCommand(command,false,value);
 const next={...item.payload,html:cleanHTML(body.innerHTML)};enqueue(id,next);if(before.html!==next.html)record([{id,before,after:clone(next)}]);S.textBefore=clone(next);if(sel.rangeCount)savedTextRange={id,range:sel.getRangeAt(0).cloneRange()};
}
$('format').addEventListener('pointerdown',e=>{if(e.target.closest('button'))e.preventDefault()});
$('format').addEventListener('click',e=>{const button=e.target.closest('[data-rich]'),color=e.target.closest('[data-color]');if(button)rich(button.dataset.rich);if(color&&S.edit&&S.selected){const p=S.items.get(S.selected)?.payload;if(p)mutate(S.selected,{...p,color:color.dataset.color})}});
$('font-family').onchange=e=>rich('fontName',e.target.value);$('font-size').onchange=e=>rich('size',e.target.value);$('text-color').oninput=e=>rich('foreColor',e.target.value);$('highlight-color').oninput=e=>rich('hiliteColor',e.target.value);
function styleSelection(patch){const p=S.items.get(S.selected)?.payload;if(S.edit&&p)mutate(S.selected,{...p,...patch})}
$('fill-color').onchange=e=>styleSelection({color:e.target.value});$('shape-kind').onchange=e=>styleSelection({shape:e.target.value});$('border-color').onchange=e=>styleSelection({borderColor:e.target.value});$('border-width').onchange=e=>styleSelection({borderWidth:Number(e.target.value)});$('border-style').onchange=e=>styleSelection({borderStyle:e.target.value});
function hideContext(){$('context-menu').hidden=true}
function menuEntry(action,label,shortcut=''){return `<button role="menuitem" data-action="${action}"><span>${label}</span><small>${shortcut}</small></button>`}
$('canvas').addEventListener('contextmenu',e=>{e.preventDefault();const node=e.target.closest('.node'),edge=e.target.closest('.edge,.edge-endpoint');select(node?.dataset.id||edge?.dataset.id||null);contextPoint=point(e);const p=S.items.get(S.selected)?.payload;let html='';if(S.edit){if(p){html+=menuEntry('duplicate','Duplicate','Ctrl+D')+menuEntry('copy','Copy object')+menuEntry('delete','Delete','Del');if(p.type!=='edge')html+=menuEntry('connect','Connect from this point')+menuEntry('front','Bring to front')+menuEntry('back','Send to back');html+='<hr>'}else{for(const type of ['note','card','text','shape'])html+=menuEntry('add-'+type,'Add '+type);html+='<hr>'}if(boardClipboard)html+=menuEntry('paste','Paste object here');if(S.history.length)html+=menuEntry('undo','Undo','Ctrl+Z');if(S.future.length)html+=menuEntry('redo','Redo','Ctrl+Shift+Z')}html+=menuEntry('fit','Fit board to screen');const menu=$('context-menu');menu.innerHTML=html;menu.hidden=false;menu.style.left=Math.max(8,Math.min(e.clientX,window.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(e.clientY,window.innerHeight-menu.offsetHeight-8))+'px';menu.querySelector('button')?.focus()});
$('context-menu').addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;hideContext();const p=S.items.get(S.selected)?.payload;if(action==='fit'){fit();return}if(!S.edit)return;if(action==='duplicate')duplicate();else if(action==='delete')removeSelected();else if(action==='undo')undo();else if(action==='redo')undo(true);else if(action==='copy'&&p){boardClipboard=clone(p);notify('Object copied')}else if(action==='paste'&&boardClipboard){if(boardClipboard.type==='edge'){notify('Duplicate the connected cards instead.');return}createNode(boardClipboard.type,{...clone(boardClipboard),x:contextPoint.x,y:contextPoint.y})}else if(action?.startsWith('add-'))createNode(action.slice(4),{x:contextPoint.x,y:contextPoint.y});else if(action==='connect'&&p&&p.type!=='edge'){tool('connect');const at=attachment(p,contextPoint);S.connectFrom={id:S.selected,side:at.side,at};notify('Click anywhere on the destination card.')}else if((action==='front'||action==='back')&&p){const levels=activeItems().map(i=>Number.isFinite(i.payload.z)?i.payload.z:0);mutate(S.selected,{...p,z:action==='front'?Math.max(0,...levels)+1:Math.min(0,...levels)-1})}});
$('context-menu').addEventListener('keydown',e=>{const buttons=[...$('context-menu').querySelectorAll('button')];let i=buttons.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus()}if(e.key==='Escape'){hideContext();$('canvas').focus()}});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#context-menu'))hideContext()});window.addEventListener('resize',hideContext);


const imageURLs=new Map();let imageHydrating=false;
async function imageLinks(paths){const {data,error}=await db.functions.invoke('studio-image-access',{body:{board_id:S.board.id,share_token:S.publicToken||undefined,paths}});if(error||data?.error)throw new Error(data?.error||'Image access unavailable');for(const row of data.urls||[])imageURLs.set(row.path,{url:row.url,until:Date.now()+240000});return data}
async function hydrateImages(){if(imageHydrating||!S.board)return;const paths=[...new Set(activeItems().filter(i=>i.payload.type==='image'&&i.payload.storagePath&&!S.pending.has(i.id)).map(i=>i.payload.storagePath))].filter(path=>!imageURLs.has(path)||imageURLs.get(path).until<Date.now());if(!paths.length)return;imageHydrating=true;const gen=S.generation;try{for(let n=0;n<paths.length;n+=50)await imageLinks(paths.slice(n,n+50));if(gen===S.generation)render()}catch(e){for(const path of paths)if(!imageURLs.has(path))imageURLs.set(path,{url:null,until:Date.now()+15000});console.warn(e.message)}finally{imageHydrating=false}}
$('nodes').addEventListener('click',async e=>{const button=e.target.closest('.image-download');if(!button)return;e.preventDefault();e.stopPropagation();const p=S.items.get(button.closest('.node').dataset.id)?.payload;if(!p)return;button.disabled=true;try{let url=p.src;if(p.storagePath){if(!imageURLs.get(p.storagePath)?.url||imageURLs.get(p.storagePath).until<Date.now())await imageLinks([p.storagePath]);url=imageURLs.get(p.storagePath)?.url}if(!url)throw new Error('Image unavailable');const response=await fetch(url);if(!response.ok)throw new Error('Download failed');const blob=await response.blob(),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=p.filename||('board-image.'+(p.src?.match(/^data:image\/(\w+)/)?.[1]||'png'));a.click();setTimeout(()=>URL.revokeObjectURL(href),60000)}catch(err){notify(err.message)}finally{button.disabled=false}});

init();
